services:
  sim_api:
    container_name: ${SERVICE_NAME}
    image: ${IMAGE}
    restart: unless-stopped
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    volumes:
      - "/home/admin/sim_config/config:/GetSIMInfoAPI/config"
    command:
      - "gunicorn"
      - "--bind"
      - "0.0.0.0:5000"
      - "--workers"
      - "4"
      - "--threads"
      - "2"
      - "app:app"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
